import { type KnowledgeBaseEntry } from "./types";

export const geneticsDb: KnowledgeBaseEntry[] = [
  {
    rsid: "rs4988235",
    gene: "LCT",
    trait: "Lactose tolerance",
    effect: "Low lactase activity may cause lactose sensitivity.",
    impact: "Likely lactose sensitivity if genotype is CC/CT.",
    recommendedFoods: ["lactose-free dairy", "aged cheeses", "kefir", "calcium-rich greens"],
    avoidFoods: ["regular milk", "soft cheeses", "large lactose loads"],
    lifestyleNotes: "Try lactose-free options and titrate dairy slowly.",
    keywords: ["lactose", "dairy", "lactase"],
    reference: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4744901/",
    riskAlleles: ["C"],
  },
  {
    rsid: "rs182549",
    gene: "MCM6",
    trait: "Lactose tolerance",
    effect: "Linked to lactase persistence in adults.",
    impact: "CC suggests higher chance of lactose intolerance.",
    recommendedFoods: ["lactose-free milk", "fermented dairy", "fortified plant milks"],
    avoidFoods: ["high-lactose milkshakes", "ice cream"],
    lifestyleNotes: "Space dairy servings and pair with meals.",
    keywords: ["lactose", "dairy"],
    riskAlleles: ["C"],
  },
  {
    rsid: "rs762551",
    gene: "CYP1A2",
    trait: "Caffeine metabolism",
    effect: "Reduced enzyme activity slows caffeine clearance.",
    impact: "Slow metabolizers may feel jittery or sleep disruption.",
    recommendedFoods: ["green tea", "decaf coffee", "hydration", "magnesium-rich foods"],
    avoidFoods: ["energy drinks", "late-day espresso"],
    lifestyleNotes: "Shift caffeine earlier; cap to <200 mg if sensitive.",
    keywords: ["caffeine", "coffee"],
    reference: "https://pubmed.ncbi.nlm.nih.gov/16522833/",
    riskAlleles: ["C"],
  },
  {
    rsid: "rs2472297",
    gene: "CYP1A2",
    trait: "Caffeine metabolism",
    effect: "Variant influences coffee intake and metabolism speed.",
    impact: "T allele often linked to higher intake without jitters.",
    recommendedFoods: ["moderate coffee", "green tea", "water"],
    avoidFoods: ["very high caffeine supplements"],
    lifestyleNotes: "Monitor sleep quality relative to caffeine timing.",
    keywords: ["caffeine", "coffee"],
    riskAlleles: ["C"],
  },
  {
    rsid: "rs5751876",
    gene: "ADORA2A",
    trait: "Caffeine sensitivity",
    effect: "A allele may increase anxiety from caffeine.",
    impact: "Higher sensitivity to stimulant effects.",
    recommendedFoods: ["decaf options", "herbal tea", "steady meals"],
    avoidFoods: ["energy drinks", "pre-workout stimulants"],
    lifestyleNotes: "Pair caffeine with food; consider smaller, earlier doses.",
    keywords: ["caffeine", "anxiety"],
    riskAlleles: ["A"],
  },
  {
    rsid: "rs9939609",
    gene: "FTO",
    trait: "Weight regulation",
    effect: "Associated with appetite and weight gain risk.",
    impact: "A allele may increase hunger and fat storage tendency.",
    recommendedFoods: ["high-fiber veggies", "lean protein", "whole grains"],
    avoidFoods: ["sugary drinks", "ultra-processed snacks"],
    lifestyleNotes: "Prioritize meal timing, resistance training, sleep.",
    keywords: ["weight", "obesity", "satiety"],
    reference: "https://pubmed.ncbi.nlm.nih.gov/28416818/",
    riskAlleles: ["A"],
  },
  {
    rsid: "rs17782313",
    gene: "MC4R",
    trait: "Appetite control",
    effect: "Variant influences appetite and BMI.",
    impact: "C allele linked to higher caloric intake.",
    recommendedFoods: ["protein at breakfast", "fiber-rich snacks", "low-glycemic meals"],
    avoidFoods: ["grazing on sweets", "liquid calories"],
    lifestyleNotes: "Plan structured meals; pair carbs with protein.",
    keywords: ["appetite", "satiety"],
    riskAlleles: ["C"],
  },
  {
    rsid: "rs1801282",
    gene: "PPARG",
    trait: "Fat metabolism",
    effect: "Variant affects insulin sensitivity and fat handling.",
    impact: "G allele may benefit from unsaturated fat emphasis.",
    recommendedFoods: ["olive oil", "nuts", "avocado", "fatty fish"],
    avoidFoods: ["trans fats", "excess saturated fat"],
    lifestyleNotes: "Combine healthy fats with vegetables; stay active.",
    keywords: ["fat", "insulin", "pparg"],
    riskAlleles: ["C"],
  },
  {
    rsid: "rs1042713",
    gene: "ADRB2",
    trait: "Exercise fat loss response",
    effect: "Variation can modulate fat loss from cardio.",
    impact: "Certain genotypes respond better to HIIT + protein.",
    recommendedFoods: ["lean protein", "omega-3", "balanced carbs around workouts"],
    avoidFoods: ["high sugar around inactivity"],
    lifestyleNotes: "Blend strength + intervals; track recovery.",
    keywords: ["exercise", "fat loss"],
    riskAlleles: ["G"],
  },
  {
    rsid: "rs6265",
    gene: "BDNF",
    trait: "Satiety & mood",
    effect: "Val66Met variant influences satiety and emotional eating.",
    impact: "Met allele may reduce satiety signaling.",
    recommendedFoods: ["protein-rich meals", "berries", "omega-3 fish"],
    avoidFoods: ["skipping meals", "refined sugar spikes"],
    lifestyleNotes: "Regular meals, sunlight, movement to support mood.",
    keywords: ["satiety", "mood", "appetite"],
    riskAlleles: ["A"],
  },
  {
    rsid: "rs174546",
    gene: "FADS1",
    trait: "Omega-3 conversion",
    effect: "Influences conversion of ALA to EPA/DHA.",
    impact: "T allele may reduce endogenous omega-3 synthesis.",
    recommendedFoods: ["fatty fish", "algae oil", "chia", "flax"],
    avoidFoods: ["high omega-6 oils in excess"],
    lifestyleNotes: "Prioritize marine omega-3 two times weekly.",
    keywords: ["omega-3", "fats"],
    riskAlleles: ["T"],
  },
  {
    rsid: "rs66698963",
    gene: "FADS2",
    trait: "Omega-6/3 balance",
    effect: "Deletion linked to altered PUFA balance.",
    impact: "May benefit from lowering omega-6 and boosting omega-3.",
    recommendedFoods: ["olive oil", "fatty fish", "walnuts"],
    avoidFoods: ["fried foods", "corn/soy oil excess"],
    lifestyleNotes: "Swap seed oils for olive/avocado oils.",
    keywords: ["omega-6", "omega-3"],
    riskAlleles: ["DEL"],
  },
  {
    rsid: "rs1229984",
    gene: "ADH1B",
    trait: "Alcohol metabolism",
    effect: "Fast metabolism may increase acetaldehyde spike.",
    impact: "May experience flushing with alcohol.",
    recommendedFoods: ["hydrate well", "eat before drinking", "B-complex foods"],
    avoidFoods: ["binges", "high-sugar cocktails"],
    lifestyleNotes: "Limit alcohol; alternate with water.",
    keywords: ["alcohol", "metabolism"],
    riskAlleles: ["A"],
  },
  {
    rsid: "rs671",
    gene: "ALDH2",
    trait: "Alcohol flush",
    effect: "Reduced enzyme activity increases acetaldehyde.",
    impact: "Higher flush and adverse effects risk.",
    recommendedFoods: ["abstain or very low alcohol", "hydration"],
    avoidFoods: ["spirits", "rapid drinking"],
    lifestyleNotes: "Consider avoiding alcohol for health and comfort.",
    keywords: ["alcohol", "flush"],
    riskAlleles: ["A"],
  },
  {
    rsid: "rs2855262",
    gene: "SOD2",
    trait: "Antioxidant capacity",
    effect: "Variant may lower mitochondrial antioxidant defense.",
    impact: "May benefit from higher antioxidant intake.",
    recommendedFoods: ["berries", "leafy greens", "vitamin C foods"],
    avoidFoods: ["excess fried foods", "smoking"],
    lifestyleNotes: "Add colorful plants daily; support recovery.",
    keywords: ["antioxidant", "vitamin c"],
    riskAlleles: ["C"],
  },
  {
    rsid: "rs10741657",
    gene: "CYP2R1",
    trait: "Vitamin D activation",
    effect: "Influences conversion to active vitamin D.",
    impact: "A allele linked to lower 25(OH)D levels.",
    recommendedFoods: ["fatty fish", "egg yolks", "vitamin D fortified foods"],
    avoidFoods: ["chronically low sun exposure without supplementation"],
    lifestyleNotes: "Check vitamin D status; consider moderate supplementation.",
    keywords: ["vitamin d"],
    riskAlleles: ["A"],
  },
  {
    rsid: "rs2282679",
    gene: "GC",
    trait: "Vitamin D transport",
    effect: "Variant can lower vitamin D binding protein efficiency.",
    impact: "May need slightly higher vitamin D intake.",
    recommendedFoods: ["salmon", "sardines", "mushrooms under UV"],
    avoidFoods: ["very low-fat diets reducing D absorption"],
    lifestyleNotes: "Pair vitamin D with meals containing healthy fats.",
    keywords: ["vitamin d", "binding"],
    riskAlleles: ["A"],
  },
  {
    rsid: "rs1801133",
    gene: "MTHFR",
    trait: "Folate metabolism",
    effect: "C677T variant reduces enzyme activity.",
    impact: "May benefit from active folate and B12 adequacy.",
    recommendedFoods: ["leafy greens", "legumes", "eggs", "B12-rich foods"],
    avoidFoods: ["very low folate diets", "excess alcohol"],
    lifestyleNotes: "Ensure regular folate/B12 intake; balance homocysteine.",
    keywords: ["folate", "homocysteine"],
    reference: "https://pubmed.ncbi.nlm.nih.gov/20363129/",
    riskAlleles: ["T"],
  },
  {
    rsid: "rs492602",
    gene: "TCN2",
    trait: "Vitamin B12 transport",
    effect: "Variant may alter B12 delivery to cells.",
    impact: "May need consistent B12 intake, especially in low-meat diets.",
    recommendedFoods: ["fish", "eggs", "dairy", "B12-fortified foods"],
    avoidFoods: ["long fasting without B12 sources"],
    lifestyleNotes: "Consider periodic B12 status checks.",
    keywords: ["b12", "cobalamin"],
    riskAlleles: ["G"],
  },
  {
    rsid: "rs2234693",
    gene: "ESR1",
    trait: "Bone health",
    effect: "Variant may influence estrogen receptor sensitivity.",
    impact: "Potentially higher calcium and vitamin D needs.",
    recommendedFoods: ["calcium-rich greens", "sesame", "fortified dairy/alternatives"],
    avoidFoods: ["very low-calcium diets"],
    lifestyleNotes: "Include resistance training for bone density.",
    keywords: ["bone", "calcium"],
    riskAlleles: ["C"],
  },
  {
    rsid: "rs662",
    gene: "PON1",
    trait: "Antioxidant enzyme activity",
    effect: "R allele lowers paraoxonase activity.",
    impact: "May benefit from higher antioxidant and HDL-supporting foods.",
    recommendedFoods: ["olive oil", "citrus", "berries", "nuts"],
    avoidFoods: ["smoking", "high trans fats"],
    lifestyleNotes: "Favor Mediterranean-style fats.",
    keywords: ["antioxidant", "hdl"],
    riskAlleles: ["G"],
  },
  {
    rsid: "rs3812316",
    gene: "MTTP",
    trait: "Fat absorption",
    effect: "Variant may reduce triglyceride rise with healthy fats.",
    impact: "Supports response to unsaturated fat rich diets.",
    recommendedFoods: ["olive oil", "nuts", "fish"],
    avoidFoods: ["heavy saturated fat"],
    lifestyleNotes: "Pair fats with fiber to modulate lipids.",
    keywords: ["triglyceride", "fat"],
    riskAlleles: ["G"],
  },
  {
    rsid: "rs5082",
    gene: "APOA2",
    trait: "Saturated fat response",
    effect: "CC genotype linked to higher BMI with high sat-fat intake.",
    impact: "Limit saturated fat; emphasize mono/omega-3 fats.",
    recommendedFoods: ["olive oil", "nuts", "fish", "lean proteins"],
    avoidFoods: ["butter-heavy meals", "processed meats"],
    lifestyleNotes: "Track saturated fat grams; prefer cooking oils over butter.",
    keywords: ["saturated fat", "apoa2"],
    riskAlleles: ["C"],
  },
  {
    rsid: "rs7903146",
    gene: "TCF7L2",
    trait: "Glucose regulation",
    effect: "T allele linked to higher post-meal glucose.",
    impact: "Lower refined carbs; add fiber and protein to meals.",
    recommendedFoods: ["beans", "whole grains", "non-starchy vegetables"],
    avoidFoods: ["sugary drinks", "refined bread"],
    lifestyleNotes: "Walk after meals; monitor carb portions.",
    keywords: ["glucose", "glycemic"],
    riskAlleles: ["T"],
  },
  {
    rsid: "rs1800795",
    gene: "IL6",
    trait: "Inflammation response",
    effect: "G allele may increase inflammatory response.",
    impact: "Anti-inflammatory diet may be helpful.",
    recommendedFoods: ["omega-3 fish", "olive oil", "berries", "turmeric"],
    avoidFoods: ["trans fats", "excess added sugar"],
    lifestyleNotes: "Prioritize sleep and recovery after exercise.",
    keywords: ["inflammation", "recovery"],
    riskAlleles: ["G"],
  },
];


